# Generated by Django 5.0.3 on 2024-03-08 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0004_class_user'),
        ('instructor', '0002_alter_instructor_options_instructor_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='instructors',
            field=models.ManyToManyField(related_name='class_instructors', to='instructor.instructor'),
        ),
    ]
