# Generated by Django 5.0.3 on 2024-03-07 14:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0004_class_user'),
        ('instructor', '0002_alter_instructor_options_instructor_order'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Scheduled',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('capacity', models.IntegerField()),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='classes.class')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='instructor.instructor')),
                ('user', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('users', models.ManyToManyField(related_name='scheduled_users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
