# Generated by Django 5.0.3 on 2024-03-07 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduled', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduled',
            name='room',
            field=models.CharField(default='TBD', max_length=50),
        ),
    ]
