# Generated by Django 5.0.3 on 2024-03-06 20:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15)),
                ('DOB', models.DateField()),
                ('image', models.ImageField(upload_to='instructors')),
                ('entry_code', models.CharField(max_length=10)),
                ('instr_type', models.CharField(max_length=50)),
                ('desc', models.TextField()),
                ('qualifications', models.JSONField()),
                ('activities', models.JSONField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
