# Generated by Django 5.0.3 on 2024-03-06 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instructor',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='instructor',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
