# Generated by Django 5.0.3 on 2024-03-05 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_image_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='link',
            field=models.CharField(default='', max_length=100),
        ),
    ]
