# Generated by Django 5.0.3 on 2024-03-05 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_image_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
