# Generated by Django 5.0.3 on 2024-03-05 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_image_link'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['order']},
        ),
    ]
