# Generated by Django 5.0.3 on 2024-03-08 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_image_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='link_text',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='link',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
