# Generated by Django 5.0.3 on 2024-03-11 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_image_link_text_alter_image_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
