# Generated by Django 5.0.3 on 2024-03-06 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0002_alter_class_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
